# Enable the required apache modules: a2enmod proxy proxy_http proxy_wstunnel
<VirtualHost *:80>
   ServerName mydns.example.com

   DocumentRoot /

   Alias "/filestorages/" "/filestorages/"

   <Directory "/filestorages/">
      Options FollowSymLinks
      AllowOverride None
      Require all granted
   </Directory>

   ProxyPass /filestorages/ !

   ProxyPreserveHost On

   # :8080 = websocket server port (change to the same port you're going to use on docker-compose.yml)
   <Location /app>
      ProxyPass ws://127.0.0.1:8080/app
      ProxyPassReverse ws://127.0.0.1:8080/app
   </Location>
   <Location /apps>
      ProxyPass http://127.0.0.1:8080/apps
      ProxyPassReverse http://127.0.0.1:8080/apps
   </Location>

   # :4000 = backend webserver port (change to the same port you're going to use on docker-compose.yml)
   <Location /api>
      ProxyPass http://127.0.0.1:4000/api
      ProxyPassReverse http://127.0.0.1:4000/api
   </Location>
   <Location /broadcasting>
      ProxyPass http://127.0.0.1:4000/broadcasting
      ProxyPassReverse http://127.0.0.1:4000/broadcasting
   </Location>

   # :80 = application server port (change to the same port you're going to use on docker-compose.yml)
   ProxyPass / http://127.0.0.1:80/
   ProxyPassReverse / http://127.0.0.1:80/
</VirtualHost>