[supervisord]
nodaemon=true

[program:apache]
command=/usr/sbin/apache2ctl -D FOREGROUND
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
autorestart=true

[program:queue-worker]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=60 --memory=512
directory=/var/www/html
stdout_logfile=/var/www/html/storage/logs/queue.log
stderr_logfile=/var/www/html/storage/logs/queue.err
autorestart=true
startretries=3

[program:reverb]
command=php /var/www/html/artisan reverb:start
directory=/var/www/html
stdout_logfile=/var/www/html/storage/logs/reverb.log
stderr_logfile=/var/www/html/storage/logs/reverb.err
autorestart=true